KNA1_MAPPING = {
    "Deudor": "kunnr",
    "País": "land1",
    "Nombre 1": "name1",
    "Población": "ort01",
    "Código postal": "pstlz",
    "Región": "regio",
    "Bloqueo de contacto central": "aufsd",
    "Conc.búsq.": "sortl",
    "Calle": "stras",
    "Teléfono 1": "telf1",
    "Nombre 2": "name2",
    "Tratamiento": "anred",
    "Creado el": "erdat",
    "Creado por": "ernam",
    "Grupo de cuentas": "ktokd",
    "Bloqueo central de contabilización": "faksd",
    "Clave de idioma": "spras",
    "Nº ident.fis.1": "stcd1",
    "Sociedad asociada": "kokrs",
    "N.I.F. comunitario": "stceg",
    "Número fiscal 5": "stcd5",
}
